kayakedu:
  slovak:
    visaTemplate: slovak-visa-mail-template.html
    visaInputFileData: D:\\installer-kayakedu-marketing-service\\inputdata\\slovak-visa-inputdata.xlsx
    email:
      receiver: info@kayakedu.in
      subject: National D Visa-For Employment Purposes